{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-mongodb-pvc
  labels:
    app: {{ .Values.app.name }}-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  {{- if .Values.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.mongodb.persistence.storageClass }}
  {{- end }}
{{- end }}

---

{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled (not .Values.mongodb.persistence.storageClass) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app.name }}-mongodb-pv
  labels:
    app: {{ .Values.app.name }}-mongodb
spec:
  capacity:
    storage: {{ .Values.mongodb.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/{{ .Values.app.name }}-mongodb
  persistentVolumeReclaimPolicy: Retain
{{- end }}
