{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-mongodb
  labels:
    app: {{ .Values.app.name }}-mongodb
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.mongodb.port }}
    targetPort: {{ .Values.mongodb.port }}
    protocol: TCP
    name: mongodb
  selector:
    app: {{ .Values.app.name }}-mongodb
{{- end }}